Repository UBC-MDS/obesity-explorer-R, pull requests merged in 2021-02, with the labels that each got.

#55 Fill smoke column with data and add text note when smoke selected
  R/helper.R
  R/plots.R
  R/text.R
  app.R
  data-raw/make-data.R
  data/ob.rda
  man/make_rate_data.Rd
  man/make_scatter_plot.Rd
  man/make_ts_plot.Rd
Labels: bug

#58 Add title to dashboard
  app.R
Labels: enhancement

#56 Update trendline size and Income level selection prompt
  R/plots.R
  app.R
Labels: aesthetics

#60 Add correct version of dplyr
  init.R
Labels: bug

#62 Switch mutate/across syntax to work in dplyr version 1.0.4 without errors
  R/plots.R
  man/make_bar_plot.Rd
  man/make_choropleth_plot.Rd
  man/make_scatter_plot.Rd
  man/make_ts_plot.Rd
  tests/testthat/test-plots.R
Labels: bug

#63 Add cards for plots on all tabs and add header for the dashboard
  R/helper.R
  app.R
Labels: aesthetics

#64 Add aesthetics to time series plot, removed partialized choropleth call
  R/plots.R
  app.R
Labels: enhancement

#65 Fix documentation to reflect updated data
  DESCRIPTION
  R/helper.R
  R/plots.R
  man/cydict.Rd
  man/make_choropleth_plot.Rd
  man/make_ts_plot.Rd
  man/ob.Rd
Labels: documentation

#66 Fix literacy rate in EDA and update regressor list
  R/helper.R
  R/plots.R
  app.R
  data-raw/processed/obesity-combo.csv
  data/ob.rda
  eda/eda_obesity.Rmd
  eda/eda_obesity.html
  eda/eda_obesity_files/figure-html/plot-obesity-smoking-1.png
  eda/eda_obesity_files/figure-html/plot-obesity-ts-1.png
Labels: bug

#67 Update time series title alignment
  R/plots.R
Labels: aesthetics

#68 Add grey countries and remove Antarctica from default view
  R/helper.R
  R/plots.R
Labels: aesthetics

#69 Memoize callbacks
  DESCRIPTION
  app.R
  init.R
Labels: enhancement

#70 Make plotly fonts consistent with the rest of the dashboard
  R/helper.R
  R/plots.R
  man/make_scatter_plot.Rd
Labels: aesthetics

#73 Add local controls for the bar plot
  R/helper.R
  R/plots.R
  R/text.R
  app.R
  inst/WORDLIST
  man/create_label.Rd
  man/make_bar_plot.Rd
  man/ob.Rd
  tests/testthat/test-helper.R
Labels: aesthetics, enhancement

#76 Update the heroku link in the Readme for the milestone4 app.
  README.md
Labels: documentation

#77 Allow users to highlight regions of the world average
  R/plots.R
  app.R
Labels: enhancement

#78 Update second Heroku link in README
  README.md
Labels: documentation

#79 Bump version number to 0.4.0
  DESCRIPTION
Labels: documentation

#74 Add the milestone 4 reflection document
  doc/reflection-milestone4.md
Labels: documentation
