Repository UBC-MDS/obesity-explorer-R, pull requests merged in 2021-01, with the labels that each got.

#5 Setup package structure
  README.md
  data/processed/country-ids.csv
  data/processed/obesity-combo.csv
Labels: documentation

#10 fix bug for filtering by year
  R/helper.R
Labels: bug

#14 Add interactive time series plot
  R/helper.R
  R/plots.R
  app.R
Labels: enhancement

#16 Update TS plot and app layout
  R/plots.R
  app.R
Labels: enhancement

#17 Add team conduct and contract files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  doc/proposal.md
  team-contract.md
Labels: documentation

#20 Small improvements to aesthetics
  R/plots.R
  app.R
Labels: enhancement

#21 Improve chart aesthetics and app layout
  R/helper.R
  R/plots.R
  app.R
Labels: enhancement
